[package]
name = "weave"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "weave"
path = "src/main.rs"

[dependencies]
bumpalo = "3.19.0"
clap = { version = "4.5.37", features = ["derive"] }
hashbrown = "0.15.4"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
num = "0.4.3"
num-traits = "0.2.19"
rand = "0.9.1"
